name: Continuous integration

on:
    push:
        branches:
            - main
            - develop
        tags:
            - '^[0-9]+\.[0-9]+\.[0-9]+(\.dev|)$'

jobs:
    ci:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Run image
              uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: "1.1.11"
            - name: Set up Git repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Git tag based version
              run: poetry version $(git describe --tags --abbrev=0)
            - name: Install everything with poetry
              run: poetry install
            - name: Black formatter
              run: poetry run black --check --diff .
            - name: Static type checking (mypy)
              run: poetry run mypy .
            - name: Unit tests
              run: poetry run pytest --cov=package tests/
            - name: Build package
              run: poetry build
            - uses: actions/upload-artifact@v2
              with:
                  name: Upload wheel
                  path: dist/package-*.whl
            - uses: actions/upload-artifact@v2
              with:
                  name: Upload tar gz
                  path: dist/package-*.tar.gz
